services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PG_DATA

  web:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command:
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations && 
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - my_media:$MEDIA_DATA
    depends_on:
      - db

  redis:
    image: redis:alpine
    volumes:
      - my_redis:$REDIS_DATA

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command:
      sh -c "python manage.py wait_for_db && 
            celery -A social_media_api worker -l info"
    depends_on:
      - db
      - web
      - redis


volumes:
  my_db:
  my_media:
  my_redis:
