# Generated by Django 5.1.1 on 2024-09-17 10:57

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="followers",
                to="social_media.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=social_media.models.profile_image_path
            ),
        ),
    ]
