# Generated by Django 5.1.1 on 2024-09-17 10:59

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_alter_profile_following_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social_media.models.post_image_path
            ),
        ),
    ]
