# Generated by Django 5.1.1 on 2024-09-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                related_name="followers", to="social_media.profile"
            ),
        ),
    ]
