# Generated by Django 5.1.1 on 2024-09-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0005_profile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="comment",
        ),
    ]
