# Generated by Django 5.1.1 on 2024-09-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0006_remove_like_comment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "owner")},
        ),
    ]
