# Generated by Django 5.1.1 on 2024-09-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0007_alter_like_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="owner",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="sender",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "author")},
        ),
    ]
