# Generated by Django 5.1.1 on 2024-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0008_rename_owner_like_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
