# Generated by Django 5.1.1 on 2024-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0009_alter_profile_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="social_media.tag"),
        ),
    ]
