# Generated by Django 5.1.1 on 2024-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0010_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
